
spring:
  profiles:
    active: dev
  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/curo
    username: # 数据库名
    password: # 密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8080
  servlet:
      context-path: /api
